
language: node_js
node_js:
  - '10'
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: examples
  target_branch: gh-pages
  on:
    branch: master
    